### ISSUE TITLE
Drain Samba returning/draining 0

### ISSUE THREAD

**Issue by nesstea** [DarkstarProject/darkstar#1291]
@maxtherabbit 
https://github.com/DarkstarProject/darkstar/blame/d28efdeab848748d5bdcac2f4058fd61f585eca4/src/map/utils/battleutils.cpp#L1017

It's random when it does, but it happens like 30% of the time.

![image](https://cloud.githubusercontent.com/assets/1483915/7116661/194c56ce-e1a8-11e4-9ffc-375fd314d640.png)

**Comment by maxtherabbit** [comment]
c'mon man don't post links to outdated code, this was fixed in ad1e91 :/

**Comment by flawd95** [comment]
I don't know about outdated code but that fix was 17 days ago.  I had just recently updated the server and it's still doing it.  It's not fixed.

**Comment by nesstea** [comment]
Come on max I'm not trolling broski. I was just trying to identify a probable location.

**Comment by maxtherabbit** [comment]
sorry for closing y'alls issues without fixing them, and thanks @flawd95 for pointing out that ad1e918 created the problem

**Comment by flawd95** [comment]
Thanks so much max!  I really really apprecate it.  Now I can start pwning again with my thf/dnc :D
