### ISSUE TITLE
Auto HP Bug

### ISSUE THREAD

**Issue by towbes** [DarkstarProject/darkstar#2274]
This is still a thing, didn't see any issues relating to it, is there already one open that someone knows about?

Occasionally players will automatically be returned to their home point upon death without any prompt to release.

**Comment by bendangelo** [comment]
This has been happening since forever. The client for some reason continuely requests to be home pointed. Don't know why

**Comment by TeoTwawki** [comment]
If anything happens while I'm mid dying, I can expect an auto homepoint to happen. Which makes it look like a timing issue to me.

**Comment by bendangelo** [comment]
Are you saying this is a race condition or some sort of issue with how we handle client packets? We need a good way to reproduce this problem to a tee for any chance of fixing it.

**Comment by TeoTwawki** [comment]
We've never been able to make it happen on demand, which I think is because of luck and precision of timing involved. You can however, have something show you an increased frequency in it happening. 

This is my line of thinking and I can't realistically prove a cause: client gets info for 2 diff things, tries to react, winds up telling server I clicked the menu thingy before its even displayed. 

Prior to our current code which drastically reduced how often this happens, I had made changes to the timing of when the server decides a player is "dead" on my own personal server, which had made it happen far less often. It was a pretty solid improvement but not a fix. I don't have those changes anymore, but I was changing **when** the moment they were officially dead was and **when** the animation happening was. Since then changes have happened in DSP that made this stop happening in 3 out of 4 deaths, it used to be far worse than it is now on stock DSP. And what DSP does now did as good a job as my hack without being a shitty hack, so I didn't keep my shitty hack.

**Comment by Fiocitrine** [comment]
I've notice it happen when a mob casts something like a tier III -ga spell and it one shots a bunch of people. Client gets confused?

**Comment by nesstea** [comment]
It usually happens when I am holding down CTRL or SHIFT when I die. It's inconsistent.

**Comment by xdemolish** [comment]
> usually happens when I am holding down CTRL or SHIFT when I die

o?
> It's inconsistent

o

**Comment by TeoTwawki** [comment]
@nesstea I think thats pure chance bud. Neither of those keys sends anything to server nor do they enter the clients selection on the window.

**Comment by Scavenge** [comment]
what if you just prevented allowing a homepoint for 60 minutes unless another trigger is set off by the player hitting the button

**Comment by bendangelo** [comment]
That won't work, this is an issue from the client side. It will repeatedly request a home point forever and don't think you'll ever see the dead ui.

**Comment by Scavenge** [comment]
so if they got a raise when this is occuring it would still be requesting the homepoint even when they are alive?

**Comment by GiggleCait** [comment]
Any word on this?

**Comment by teschnei** [comment]
Ah yes, this should be fixed as of a week or so ago

**Comment by Arximiro** [comment]
This issue still happens pretty regularly on Nasomi. Anyone else having it happen on their servers?

**Comment by Mizzguy** [comment]
It happens alot on my server as well (hokutens)
