### ISSUE TITLE
Antlions that ambush remain untargetable/spam Pit Ambush

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2826]
Client Version (type /ver in game) :
30160203_0

Server Version (type @revision in game) :
3a852af

Source Branch (master/stable) :
master

Additional Information (Steps to reproduce/Expected behavior) :
Same issue as chigoes, different method of being hidden, it seems.

**Comment by tagban** [comment]
This issue also happens on retail sometimes...

**Comment by tagban** [comment]
Just disabled aggro for now on these, did the same with Chigoe.

**Comment by teschnei** [comment]
chigoe have been fixed for a while

**Comment by tagban** [comment]
I updated a week ago and had people still getting killed but just updated
today again so will test..

**Comment by Hozu** [comment]
So after implementing a binding for HideModel, calling upon it in the Pit Ambush script, removing the special skill mobmod from the DB AND the core for mobs with the ambush flag, and even trying making them not be set to hide/name hidden on spawn, I still can't get them to unhide. They seem to be set to hide every tick or something and I can't figure out where.

**Comment by Hozu** [comment]
Oh this gets even better, I put a breakpoint on CMobEntity::HideModel and commented it out from being called in the roam check. It triggered when it used Pit Ambush via the lua binding I added, but it never unhid. And the breakpoint was never triggered again. ???????????

**Comment by Hozu** [comment]
Never mind it was the hidename thing... damn it. That should have been obvious.
