### ISSUE TITLE
BST_ variable length issue_job ability "Ready"

### ISSUE THREAD

**Issue by MoguSN** [DarkstarProject/darkstar#4442]
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**  30171205_0

**_Server Version_** (type `!revision` in game) **:**  86f9522227f1c6be428514a0c43082511ffddc79

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** Could not reproduce as of yet. Cause my Beast master to have an infinite number of pet charges allowing me to spam all pet "ready" abilities with out delay or cool down. 
![img_20171231_102917](https://user-images.githubusercontent.com/34987439/34463486-e8a06418-ee22-11e7-9a4f-913de7b625cb.png)

**Comment by ShelbyZ** [comment]
I was not able to reproduce this on any BST level with jug pets.  Are there any straightforward steps that allowed you to get to this point?

**Comment by MoguSN** [comment]
No, unfortunately I was not able to reproduce either.

**Comment by teschnei** [comment]
We had seen this with Quick draw as well, because they are both abilities
with charges. Maybe stratagems too, but nobody ever reported that one.

**Comment by ShelbyZ** [comment]
We addressed negative charges awhile back to avoid this exact issue.

**Comment by TeoTwawki** [comment]
> We had seen this with Quick draw as well,

Still seeing it. And can never repro on a local copy, only on a crowded server with 100+ ppl doing things.

**Comment by ShelbyZ** [comment]
https://github.com/DarkstarProject/darkstar/commit/f06d28f70e28a00606da4b17cb65d64be6a8a610 - Was related to shared recast of sic/ready and was able to get negative values at the time, but maybe I'm wrong here.

**Comment by aizenmyou** [comment]
I was in a party with @MoguSN as a BST75 and I could not reproduced. He used several jugs and they all had that number which is remarkably close to a 16bit signed INT size (65535). After /shutdown (not /logout) the issue vanished. We also had another BST51 there that could not reproduce it either.
